name: HEXO DEPLOY

on:
  workflow_dispatch:
  push:
    branches:
    - blog

jobs:
  publish:
    runs-on: ubuntu-last
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "私钥配置完成....."
          ssh-keygen github.com >> ~/.ssh/known_hosts
          git config --local user.name "wakaka378"
          git config --local user.email "wakaka"
      
      - name: Install dependencies
        run: |
          npm i -g hexo-cli
          npm i
      - name: Deploy hexo
        run: |
          hexo clean && hexo g && hexo deploy
